name: Check Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Git Secrets
        run: |
          sudo apt-get install git-secrets

      - name: Scan for secrets
        run: git secrets --scan
